### ISSUE TITLE
fix: 크로마틱 이슈 디버깅

### ISSUE THREAD

**Issue by shinhyojeong** [price-offer/offer-design-system#181]
### 📌 작업 내용

- 크로마틱 배포 터지는 이슈 디버깅

### ✅ 상세 작업

- [ ] 크로마틱 배포 터지는 이슈 디버깅

**Comment by sonsurim** [comment]
@shinhyojeong 님 요거 작업 아직 진행 안되었으면 제가 하겠습니다!
