### ISSUE TITLE
chore: Icon 컴포넌트 수정 사항 적용

### ISSUE THREAD

**Issue by shinhyojeong** [price-offer/offer-design-system#60]
### 📌 작업 내용

- Icon 컴포넌트 변경된 부분을 적용

### ✅ 상세 작업

- [ ] Carousel 컴포넌트에서 iconType => type으로 prop 변경
- [ ] Button 컴포넌트에서 iconType => type으로 prop 변경

**Comment by sonsurim** [comment]
요 작업 #59 에서 같이 진행하겠슴니둥!!
