### ISSUE TITLE
refactor: Text 컴포넌트 적용

### ISSUE THREAD

**Issue by shinhyojeong** [price-offer/offer-design-system#83]
### 📌 작업 내용

- text가 사용되는 모든 컴포넌트를 Text컴포넌트를 사용하도록 대체

### ✅ 상세 작업

- [ ] Badge
- [ ] ChattingBubble
- [ ] ImageUploader
- [ ] Input
- [ ] Radio
- [ ] SelectBox
- [ ] Textarea

**Comment by sonsurim** [comment]
디렉토리 변경 이슈로 인해 #100 에서 진행 하였습니다.
