### ISSUE TITLE
fix: Input(Price format) 18자리 수부터 0으로 입력되는 문제

### ISSUE THREAD

**Issue by manudeli** [price-offer/offer-design-system#95]
### 📌 Price Input이 18자리 수부터 0으로 입력되는 문제
가격에 이렇게 엄청 큰 숫자가 없기는 할 거 같지만 price-offer인 만큼 이런 예외 가격이 있는 것도 짚고 가면 좋을 거 같아서 이슈로 남겨요
![chrome-capture-2022-9-16](https://user-images.githubusercontent.com/61593290/196014395-788975ad-4860-4262-a180-70a3fb2bf6d2.gif)

### 🔗 관련 스토리북 링크
https://630c98d15c06a386dbef7c66-ddroqybbzq.chromatic.com/?path=/story/components-input--default

### 예상되는 이유
bigInt의 경우 자바스크립트에서 처리를 같게 하기 때문이 아닐까 싶어요

<img width="425" alt="image" src="https://user-images.githubusercontent.com/61593290/196014552-1da1739a-c12b-411c-a98f-496d8d982b1c.png">

### 이러한 경우도 처리되는 MUI - number format 통합 예시
🔗 https://mui.com/material-ui/react-text-field/#integration-with-3rd-party-input-libraries
![chrome-capture-2022-9-16 (1)](https://user-images.githubusercontent.com/61593290/196014624-af00f4b0-ac5d-4bae-8dbf-e1d3eb210ac0.gif)

**Comment by sonsurim** [comment]
끄앙 고마워 종현!!! @shinhyojeong 가즈아ㅏ

**Comment by manudeli** [comment]
뭔가 연관된 MDN문서인거 같아서 남겨
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

토스 slash 라이브러리에서도 비슷한 이슈를 고민한 분이 있더라구
https://github.com/toss/slash/issues/71

**Comment by shinhyojeong** [comment]
감사합니다 종현님 🤩

**Comment by HoseungJang** [comment]
@manudeli 토스 이슈에서 넘어왔습니다. (현재 close)
일반적으로 저렇게 큰 정수값을 사용하게될 경우가 매우 적습니다. 그런 경우가 있더라도, 시스템의 처리 범위 바깥의 큰 정수값은 string + 정규표현식으로 관리하는게 올바른 것 같고, 딱히 라이브러리 이슈라고 생각되진 않습니다.
따라서 해당 이슈의 주인공인 `commaizeNumber` 유틸도 [인자로 string을 받습니다.](https://github.com/toss/slash/blob/11c50d95e764cfe0db87327f4bc5afc1a54a418b/packages/common/utils/src/Numbers.ts#L153)

https://github.com/toss/slash/issues/71#issuecomment-1288196080
